ARG PYTHON_VERSION=3.9
ARG NLP_VERSION=0.3.0

FROM python:${PYTHON_VERSION}-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt update \
    && apt install -y build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install nlp-service[server] \
    && python -m spacy download en_core_web_lg
